# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

# hand-written Verilog stubs for the imported modules (iverilog link checks)
KEEPFILES = VColl5.v VShared.v

include $(CONFDIR)/clean.mk
