if { $systemctest == 1 } {

compile_object_pass Methods.bsv
create_systemc_objects_fail_error sysMethods.bsched sysMethods S0064 1 {-systemc}

compile_object_pass Path.bsv
create_systemc_objects_fail_error sysPath.bsched sysPath S0063 1 {-systemc}

compile_object_pass ModuleArg.bsv
create_systemc_objects_fail_error sysModuleArg.bsched sysModuleArg G0099 1 {-systemc}

compile_object_pass ModuleParam.bsv
create_systemc_objects_fail_error sysModuleParam.bsched sysModuleParam G0099 1 {-systemc}

compile_object_pass RuleBeforeMethod.bsv
create_systemc_objects_fail_error sysRuleBeforeMethod.bsched sysRuleBeforeMethod S0067 1 {-systemc}

compile_object_pass RenamedClockClash.bsv
create_systemc_objects_pass sysRenamedClockClash.bsched sysRenamedClockClash
}
