#!/usr/bin/env python3
"""Turn `trs specializations` manifests into build rules.

Reads only the JSON manifests -- trs emits facts, a build integration
decides what they mean.  Three back-ends, because the three build
systems differ in how a generated graph is allowed to enter them:

  make    a generated .mk the top Makefile includes
  ninja   a generated build.ninja
  bazel   generated .bzl, plus a check target that fails when the
          checked-in copy no longer matches what this would emit

The graph is the same in all three, and it is the point: a SPECIALIZATION is a
node, a design depends on the classes it needs, and no design depends
on another design.  One design owning the shared objects would mean
the other could not build without it.
"""
import argparse, glob, json, os, sys


def load(paths):
    """manifests -> (specializations by object name, units)."""
    specs, units = {}, {}
    for p in paths:
        m = json.load(open(p))
        units[m["top"]] = m
        for c in m["specializations"]:
            prev = specs.get(c["object"])
            if prev and prev["sig"] != c["sig"]:
                sys.exit(f"{c['object']}: two signatures for one object name")
            specs[c["object"]] = c
    return specs, units


def binds(c):
    return " ".join(f"+{k}={v}" for k, v in sorted(c["params"].items()))


def closure(specs, objs):
    """objs plus everything they transitively need."""
    seen, stack = set(), list(objs)
    while stack:
        o = stack.pop()
        if o in seen:
            continue
        seen.add(o)
        stack.extend(specs[o]["needs"] if o in specs else [])
    return sorted(seen)


def make(specs, units, out):
    w = out.write
    w("# generated by trs-spec-rules.py -- do not edit\n\n")
    for obj, c in sorted(specs.items()):
        stem = obj[:-2]
        # depends on what it DIRECTLY instantiates, and takes those as
        # inputs -- so compiling it reuses them instead of rebuilding
        # them into its own output directory
        need = closure(specs, c["needs"])
        deps = " ".join(f"$(OBJDIR)/{n[:-2]}/{n}" for n in need)
        ins = ":".join(f"$(OBJDIR)/{n[:-2]}" for n in need) or "/dev/null"
        w(f"$(OBJDIR)/{stem}/{obj}: $(BIRDIR)/{c['fragment']} {deps}\n")
        w(f"\t@mkdir -p $(@D)\n")
        w(f"\t$(TRS) link $< {binds(c)} -o $(OBJDIR)/{stem}/link.exe\n")
        w(f"\t$(TRS) compile $(OBJDIR)/{stem}/link.exe.bir"
          f" --spec-obj-in {ins} --spec-obj-out $(@D)\n\n")
    for top, m in sorted(units.items()):
        deps = " ".join(f"$(OBJDIR)/{c['object'][:-2]}/{c['object']}" for c in m["specializations"])
        ins = ":".join(f"$(OBJDIR)/{c['object'][:-2]}" for c in m["specializations"])
        w(f"$(SODIR)/{top}.so: $(BIRDIR)/{top}.exe.bir {deps}\n")
        w(f"\t@mkdir -p $(@D)\n")
        w(f"\t$(TRS) compile $< --spec-obj-in {ins} -o $@\n\n")
    w("ALL_SO := " + " ".join(f"$(SODIR)/{t}.so" for t in sorted(units)) + "\n")


def ninja(specs, units, out):
    w = out.write
    w("# generated by trs-spec-rules.py -- do not edit\n")
    w("rule specobj\n  command = $trs link $in $binds -o $stem/link.exe && "
      "$trs compile $stem/link.exe.bir --spec-obj-in $ins --spec-obj-out $outdir\n"
      "  description = SPEC $out\n\n")
    w("rule designso\n  command = $trs compile $in --spec-obj-in $ins -o $out\n"
      "  description = LINK $out\n\n")
    for obj, c in sorted(specs.items()):
        stem = f"$objdir/{obj[:-2]}"
        need = closure(specs, c["needs"])
        deps = " ".join(f"$objdir/{n[:-2]}/{n}" for n in need)
        ins = ":".join(f"$objdir/{n[:-2]}" for n in need) or "/dev/null"
        bar = f" | {deps}" if deps else ""
        w(f"build {stem}/{obj}: specobj $birdir/{c['fragment']}{bar}\n")
        w(f"  stem = {stem}\n  outdir = {stem}\n  binds = {binds(c)}\n  ins = {ins}\n")
    w("\n")
    for top, m in sorted(units.items()):
        deps = " ".join(f"$objdir/{c['object'][:-2]}/{c['object']}" for c in m["specializations"])
        ins = ":".join(f"$objdir/{c['object'][:-2]}" for c in m["specializations"])
        w(f"build $sodir/{top}.so: designso $birdir/{top}.exe.bir | {deps}\n  ins = {ins}\n")
    w("\ndefault " + " ".join(f"$sodir/{t}.so" for t in sorted(units)) + "\n")


def bazel(specs, units, out):
    w = out.write
    w('"""generated by trs-spec-rules.py -- do not edit.\n\n')
    w("Regenerate with //tools:regen_trs_specializations; the check target fails\n")
    w('the build when this file no longer matches the manifests."""\n\n')
    w("TRS_SPECIALIZATIONS = {\n")
    for obj, c in sorted(specs.items()):
        w(f'    "{obj}": {{\n')
        w(f'        "module": "{c["module"]}",\n        "sig": "{c["sig"]}",\n')
        w(f'        "fragment": "{c["fragment"]}",\n')
        w(f'        "params": {json.dumps(c["params"])},\n')
        w(f'        "needs": {json.dumps(c["needs"])},\n    }},\n')
    w("}\n\nTRS_DESIGNS = {\n")
    for top, m in sorted(units.items()):
        w(f'    "{top}": [\n')
        for c in m["specializations"]:
            w(f'        "{c["object"]}",\n')
        w("    ],\n")
    w("}\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifests", nargs="+")
    ap.add_argument("--format", required=True, choices=("make", "ninja", "bazel"))
    ap.add_argument("-o", default="-")
    a = ap.parse_args()
    paths = [p for g in a.manifests for p in (glob.glob(g) or [g])]
    specs, units = load(paths)
    out = sys.stdout if a.o == "-" else open(a.o, "w")
    {"make": make, "ninja": ninja, "bazel": bazel}[a.format](specs, units, out)
    if out is not sys.stdout:
        out.close()
    print(f"{len(specs)} specializations, {len(units)} designs -> {a.o}", file=sys.stderr)


main()
