#!/usr/bin/env python3
"""Turn `trs specializations` manifests into build rules.

Reads only the JSON manifests -- trs emits facts, a build integration
decides what they mean.  Three back-ends, because the three build
systems differ in how a generated graph is allowed to enter them:

  make    a generated .mk the top Makefile includes
  ninja   a generated build.ninja
  bazel   generated .bzl, plus a check target that fails when the
          checked-in copy no longer matches what this would emit

The graph is the same in all three, and it is the point: a SPECIALIZATION is a
node, a design depends on the classes it needs, and no design depends
on another design.  One design owning the shared objects would mean
the other could not build without it.
"""
import argparse, glob, json, os, sys


def load(paths):
    """manifests -> (specializations by object name, units, model producers)."""
    specs, units, models = {}, {}, {}
    for p in paths:
        m = json.load(open(p))
        units[m["top"]] = m
        # A verilated model is built from a FRAGMENT, and `trs vlt
        # build` takes no bindings -- it walks the whole subtree and
        # builds every class, forwarded parameters included.  So the
        # producer is any fragment that names the model; pick one, so
        # two specializations of one fragment do not become two rules
        # writing one file.
        for c in m["specializations"]:
            prev = specs.get(c["object"])
            if prev and prev["sig"] != c["sig"]:
                sys.exit(f"{c['object']}: two signatures for one object name")
            specs[c["object"]] = c
            for md in c.get("models", []):
                models.setdefault(md["run_key"],
                                  {"verilog": md["verilog"], "fragment": c["fragment"]})
        for md in m.get("models", []):
            models.setdefault(md["run_key"],
                              {"verilog": md["verilog"], "fragment": m["top"] + ".exe.bir"})
    return specs, units, models


def model_keys(specs, objs, own=()):
    """run keys `own` plus every model the closure of `objs` needs.

    A compile runs the fragment's reset window, which instantiates the
    imported models -- so the models of everything underneath are
    needed too, not only the direct imports.
    """
    ks = set(own)
    for o in closure(specs, objs):
        for md in specs.get(o, {}).get("models", []):
            ks.add(md["run_key"])
    return sorted(ks)


def binds(c):
    return " ".join(f"+{k}={v}" for k, v in sorted(c["params"].items()))


def closure(specs, objs):
    """objs plus everything they transitively need."""
    seen, stack = set(), list(objs)
    while stack:
        o = stack.pop()
        if o in seen:
            continue
        seen.add(o)
        stack.extend(specs[o]["needs"] if o in specs else [])
    return sorted(seen)


def make(specs, units, models, out):
    w = out.write
    w("# generated by trs-spec-rules.py -- do not edit\n\n")
    # verilated models: `trs vlt build` writes <cache>/vlt/byid/<run
    # key>, so the run key IS the target name.  Unlike the cache's
    # class key it carries no absolute paths, which is what lets the
    # rule be written at all.
    for key, md in sorted(models.items()):
        w(f"$(VLTCACHE)/vlt/byid/{key}: $(BIRDIR)/{md['fragment']}\n")
        w(f"\t$(TRS) vlt build $< --cache $(VLTCACHE)\n\n")
    def mdeps(keys):
        return " ".join(f"$(VLTCACHE)/vlt/byid/{k}" for k in keys)
    for obj, c in sorted(specs.items()):
        stem = obj[:-2]
        # depends on what it DIRECTLY instantiates, and takes those as
        # inputs -- so compiling it reuses them instead of rebuilding
        # them into its own output directory
        need = closure(specs, c["needs"])
        deps = " ".join(f"$(OBJDIR)/{n[:-2]}/{n}" for n in need)
        ins = ":".join(f"$(OBJDIR)/{n[:-2]}" for n in need) or "/dev/null"
        mk = mdeps(model_keys(specs, c["needs"],
                              [md["run_key"] for md in c.get("models", [])]))
        w(f"$(OBJDIR)/{stem}/{obj}: $(BIRDIR)/{c['fragment']} {deps} {mk}\n")
        w(f"\t@mkdir -p $(@D)\n")
        w(f"\t$(TRS) link $< {binds(c)} -o $(OBJDIR)/{stem}/link.exe\n")
        w(f"\t$(TRS) compile $(OBJDIR)/{stem}/link.exe.bir"
          f" --spec-obj-in {ins} --spec-obj-out $(@D)\n\n")
    for top, m in sorted(units.items()):
        objs = [c["object"] for c in m["specializations"]]
        deps = " ".join(f"$(OBJDIR)/{o[:-2]}/{o}" for o in objs)
        ins = ":".join(f"$(OBJDIR)/{o[:-2]}" for o in objs)
        mk = mdeps(model_keys(specs, objs,
                              [md["run_key"] for md in m.get("models", [])]))
        w(f"$(SODIR)/{top}.so: $(BIRDIR)/{top}.exe.bir {deps} {mk}\n")
        w(f"\t@mkdir -p $(@D)\n")
        w(f"\t$(TRS) compile $< --spec-obj-in {ins} -o $@\n\n")
    w("ALL_SO := " + " ".join(f"$(SODIR)/{t}.so" for t in sorted(units)) + "\n")


def ninja(specs, units, models, out):
    w = out.write
    w("# generated by trs-spec-rules.py -- do not edit\n")
    w("rule vltmodel\n  command = $trs vlt build $in --cache $vltcache\n"
      "  description = VLT $out\n\n")
    w("rule specobj\n  command = $trs link $in $binds -o $stem/link.exe && "
      "$trs compile $stem/link.exe.bir --spec-obj-in $ins --spec-obj-out $outdir\n"
      "  description = SPEC $out\n\n")
    w("rule designso\n  command = $trs compile $in --spec-obj-in $ins -o $out\n"
      "  description = LINK $out\n\n")
    # the run key is the byid file `trs vlt build` writes -- a real
    # output path, so a model is an ordinary ninja node
    for key, md in sorted(models.items()):
        w(f"build $vltcache/vlt/byid/{key}: vltmodel $birdir/{md['fragment']}\n")
    w("\n")
    def mdeps(keys):
        return " ".join(f"$vltcache/vlt/byid/{k}" for k in keys)
    for obj, c in sorted(specs.items()):
        stem = f"$objdir/{obj[:-2]}"
        need = closure(specs, c["needs"])
        deps = " ".join(f"$objdir/{n[:-2]}/{n}" for n in need)
        ins = ":".join(f"$objdir/{n[:-2]}" for n in need) or "/dev/null"
        mk = mdeps(model_keys(specs, c["needs"],
                              [md["run_key"] for md in c.get("models", [])]))
        all_deps = " ".join(x for x in (deps, mk) if x)
        bar = f" | {all_deps}" if all_deps else ""
        w(f"build {stem}/{obj}: specobj $birdir/{c['fragment']}{bar}\n")
        w(f"  stem = {stem}\n  outdir = {stem}\n  binds = {binds(c)}\n  ins = {ins}\n")
    w("\n")
    for top, m in sorted(units.items()):
        objs = [c["object"] for c in m["specializations"]]
        deps = " ".join(f"$objdir/{o[:-2]}/{o}" for o in objs)
        ins = ":".join(f"$objdir/{o[:-2]}" for o in objs)
        mk = mdeps(model_keys(specs, objs,
                              [md["run_key"] for md in m.get("models", [])]))
        all_deps = " ".join(x for x in (deps, mk) if x)
        bar = f" | {all_deps}" if all_deps else ""
        w(f"build $sodir/{top}.so: designso $birdir/{top}.exe.bir{bar}\n  ins = {ins}\n")
    w("\ndefault " + " ".join(f"$sodir/{t}.so" for t in sorted(units)) + "\n")


def bazel(specs, units, models, out):
    w = out.write
    w('"""generated by trs-spec-rules.py -- do not edit.\n\n')
    w("Regenerate with //tools:regen_trs_specializations; the check target fails\n")
    w('the build when this file no longer matches the manifests."""\n\n')
    w("TRS_SPECIALIZATIONS = {\n")
    for obj, c in sorted(specs.items()):
        w(f'    "{obj}": {{\n')
        w(f'        "module": "{c["module"]}",\n        "sig": "{c["sig"]}",\n')
        w(f'        "fragment": "{c["fragment"]}",\n')
        w(f'        "params": {json.dumps(c["params"])},\n')
        w(f'        "needs": {json.dumps(c["needs"])},\n')
        # the models this specialization needs BUILT before it
        # compiles -- closure, because the reset window it bakes
        # instantiates everything underneath it too
        w('        "models": %s,\n    },\n' % json.dumps(
            model_keys(specs, c["needs"], [md["run_key"] for md in c.get("models", [])])))
    w("}\n\n# run key -> (Verilog top, the fragment `trs vlt build` builds it from).\n")
    w("# The key is the byid file name, so it is a stable label for a\n")
    w("# model target; the cache's CLASS key is not (it hashes absolute paths).\n")
    w("TRS_VLT_MODELS = {\n")
    for key, md in sorted(models.items()):
        w(f'    "{key}": {{"verilog": "{md["verilog"]}", "fragment": "{md["fragment"]}"}},\n')
    w("}\n\nTRS_DESIGNS = {\n")
    for top, m in sorted(units.items()):
        objs = [c["object"] for c in m["specializations"]]
        w(f'    "{top}": {{\n        "objects": {json.dumps(objs)},\n')
        w('        "models": %s,\n    },\n' % json.dumps(
            model_keys(specs, objs, [md["run_key"] for md in m.get("models", [])])))
    w("}\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifests", nargs="+")
    ap.add_argument("--format", required=True, choices=("make", "ninja", "bazel"))
    ap.add_argument("-o", default="-")
    a = ap.parse_args()
    paths = [p for g in a.manifests for p in (glob.glob(g) or [g])]
    specs, units, models = load(paths)
    out = sys.stdout if a.o == "-" else open(a.o, "w")
    {"make": make, "ninja": ninja, "bazel": bazel}[a.format](specs, units, models, out)
    if out is not sys.stdout:
        out.close()
    print(f"{len(specs)} specializations, {len(models)} models, "
          f"{len(units)} designs -> {a.o}", file=sys.stderr)


main()
