-- | Changes made while scheduling and validating an elaborated module.
-- The original rule bodies remain in the module artifact. This patch stores
-- only added definitions/rules, removals, and scheduled ready values; the
-- fixed rule-guard rewrite is replayed when the two artifacts are combined.
module ASchedulePatch
    ( ASchedulePatch(..)
    , diffASchedulePatch
    , applyASchedulePatch
    , scheduleRuleGuard
    , scheduleIfcRuleGuards
    ) where

import qualified Data.Map.Strict as M
import qualified Data.Set as S

import ASyntax
    ( APackage(..), ADef(..), ARule(..), AIFace(..), aRuleName )
import ASyntaxUtil (aBoolVar)
import Backend (Backend)
import Id (Id, isRdyId, mkIdCanFire)

-- | This is the patch up to proof checking and post-schedule path analysis,
-- before noinline lowering and schedule-assumption instrumentation.
-- The enclosing schedule artifact must identify the exact input module.
data ASchedulePatch = ASchedulePatch
    { asp_module :: Id
    , asp_backend :: Maybe Backend
    , asp_removed_defs :: [Id]
    , asp_added_defs :: [ADef]
    , asp_removed_rules :: [Id]
    , asp_added_rules :: [ARule]
    , asp_ready_values :: [(Id, ADef)]
    } deriving (Eq, Show)

-- | User and interface rules both retain their bodies and obtain a guard
-- referring to the CAN_FIRE definition generated by AAddScheduleDefs.
scheduleRuleGuard :: ARule -> ARule
scheduleRuleGuard rule =
    rule { arule_pred = aBoolVar (mkIdCanFire (aRuleName rule)) }

scheduleIfcRuleGuards :: AIFace -> AIFace
scheduleIfcRuleGuards method@(AIAction { aif_body = rules }) =
    method { aif_body = map scheduleRuleGuard rules }
scheduleIfcRuleGuards method@(AIActionValue { aif_body = rules }) =
    method { aif_body = map scheduleRuleGuard rules }
scheduleIfcRuleGuards method = method

-- | Record the narrow changes supported above. Replay is checked against
-- the scheduler result so a future transformation cannot silently lose a
-- changed rule body, definition, instance, interface member, or other field.
-- ASyntax equality ignores some source metadata, so the artifact writer
-- must additionally compare encodings of the replayed and original result.
diffASchedulePatch :: APackage -> APackage -> Either String ASchedulePatch
diffASchedulePatch before after = do
    ensure (null (apkg_proof_obligations after))
        "cannot record a schedule with pending proof obligations"
    unique "scheduled definition" (map adef_objid (apkg_local_defs after))
    unique "scheduled rule" (map arule_id (apkg_rules after))
    unique "scheduled interface" (map aif_name (apkg_interface after))
    let beforeDefs = S.fromList (map adef_objid (apkg_local_defs before))
        afterDefs = S.fromList (map adef_objid (apkg_local_defs after))
        beforeRules = S.fromList (map arule_id (apkg_rules before))
        afterRules = S.fromList (map arule_id (apkg_rules after))
        patch = ASchedulePatch
            { asp_module = apkg_name before
            , asp_backend = apkg_backend after
            , asp_removed_defs =
                [ adef_objid def | def <- apkg_local_defs before
                , adef_objid def `S.notMember` afterDefs ]
            , asp_added_defs =
                [ def | def <- apkg_local_defs after
                , adef_objid def `S.notMember` beforeDefs ]
            , asp_removed_rules =
                [ arule_id rule | rule <- apkg_rules before
                , arule_id rule `S.notMember` afterRules ]
            , asp_added_rules =
                [ rule | rule <- apkg_rules after
                , arule_id rule `S.notMember` beforeRules ]
            , asp_ready_values =
                [ (name, value)
                | AIDef { aif_name = name, aif_value = value } <- apkg_interface after
                , isRdyId name ]
            }
    replayed <- applyASchedulePatch before patch
    ensure (replayed == after)
        "scheduling changed a module field not represented by its schedule patch"
    return patch

-- | Reconstruct scheduled ASyntax without rerunning the scheduler or SAT
-- checks. Original bodies are reused; successful scheduling has discharged
-- the proof obligations. Invalid IDs are rejected rather than ignored.
applyASchedulePatch :: APackage -> ASchedulePatch -> Either String APackage
applyASchedulePatch before patch = do
    ensure (apkg_name before == asp_module patch)
        "schedule patch belongs to a different module"
    let defs = apkg_local_defs before
        rules = apkg_rules before
        ifc = apkg_interface before
        defIds = map adef_objid defs
        ruleIds = map arule_id rules
        addedDefIds = map adef_objid (asp_added_defs patch)
        addedRuleIds = map arule_id (asp_added_rules patch)
        readyIds = [ name | AIDef { aif_name = name } <- ifc, isRdyId name ]
        removedDefs = S.fromList (asp_removed_defs patch)
        removedRules = S.fromList (asp_removed_rules patch)
        readyValues = M.fromList (asp_ready_values patch)
    unique "input definition" defIds
    unique "input rule" ruleIds
    unique "input interface" (map aif_name ifc)
    unique "added definition" addedDefIds
    unique "added rule" addedRuleIds
    unique "removed definition" (asp_removed_defs patch)
    unique "removed rule" (asp_removed_rules patch)
    unique "ready replacement" (map fst (asp_ready_values patch))
    subset "removed definition" (asp_removed_defs patch) defIds
    subset "removed rule" (asp_removed_rules patch) ruleIds
    subset "ready replacement" (map fst (asp_ready_values patch)) readyIds
    disjoint "added definition already exists in the input module" addedDefIds defIds
    disjoint "added rule already exists in the input module" addedRuleIds ruleIds
    let replaceReady method@(AIDef { aif_name = name }) =
            case M.lookup name readyValues of
                Just value -> method { aif_value = value }
                Nothing -> method
        replaceReady method = method
    return before
        { apkg_backend = asp_backend patch
        , apkg_local_defs =
            filter ((`S.notMember` removedDefs) . adef_objid) defs ++ asp_added_defs patch
        , apkg_rules = map scheduleRuleGuard
            (filter ((`S.notMember` removedRules) . arule_id) rules ++ asp_added_rules patch)
        , apkg_interface = map (scheduleIfcRuleGuards . replaceReady) ifc
        , apkg_proof_obligations = []
        }

ensure :: Bool -> String -> Either String ()
ensure True _ = Right ()
ensure False message = Left message

unique :: String -> [Id] -> Either String ()
unique label ids = ensure (length ids == S.size (S.fromList ids))
    ("duplicate " ++ label ++ " IDs in schedule patch")

subset :: String -> [Id] -> [Id] -> Either String ()
subset label ids allowed = ensure (S.fromList ids `S.isSubsetOf` S.fromList allowed)
    ("unknown " ++ label ++ " ID in schedule patch")

disjoint :: String -> [Id] -> [Id] -> Either String ()
disjoint message left right = ensure
    (S.null (S.intersection (S.fromList left) (S.fromList right))) message
