#!/usr/bin/env python3
"""compare.py -- the comparison step of the bsc determinism gate.

usage: compare.py <archiveA> <archiveB> --allowlist F --ignore F --out PREFIX
                  [--scope-groups "g1 g2 ..."] [--write-allowlist F]
                  [--allow-stale] [--root-counts] [--jobs N]

Compares two archives written by archive-pass.sh (normally A = a plain run of
the testsuite and B = the same run with -reverse-intern-order) and decides
whether the differences are exactly the ones already known.

Every regular file under either archive takes part, except the _sum/ and _log/
directories and the files time.out and groups.list.  Paths are relative to the
archive root, which is the testsuite directory, with no leading './'.

  ignore.txt     one pattern per line, TAB-separated: fnmatch glob, reason.
                 Matched against the relative path.  Files that match are left
                 out of the comparison entirely.  Only for test-harness noise
                 that is not compiler ordering (wall-clock text, process
                 addresses, time-seeded generators, RTS statistics, binaries).
  allowlist.txt  one entry per line, TAB-separated: path, root_id, note.
                 The files known to differ today, each tied to the root cause
                 that the determinism work still has to fix.  The list only
                 shrinks: an entry whose file no longer differs is stale.
  '#' lines and blank lines are comments in both.

Before bytes are compared a few normalisers run (and nowhere else); each
one touches exactly one kind of line that no compiler ordering can reach, and
check-normalisers.py exercises each on captured samples:
  .v .sv .cxx .h .c   drop lines matching '^// (On|Generated by) ' and
                      '^ \\* On ', and lines containing '--creation_time'
  model_*.cxx         also drop get_creation_time's build time: the
                      '  /* <ctime> */' line and the '  return <n>llu;' line
                      right after it (SimBlocksToC.hs gct_def; zero under
                      -no-show-timestamps, the wall clock without it)
  .vcd, .fst-vcd      drop the $date ... $end section (.fst-vcd is the VCD that
                      fst2vcd writes from an FST dump in bsc.bluesim/fst)
  *.inline-reg, *.no-inline-reg (vvp text dumps)
                      replace 0x[0-9a-fA-F]+ with 0xADDR
  .bsc-out, .bsc-<step>-out (bsc transcripts: .bsc-vcomp-out, .bsc-ccomp-out,
  .bsc-regen-out, .bsc-vgen-out, ...)
                      read 'Verilog file reused:' and '<engine> object reused:'
                      as 'created:' (bsc.hs reuseVerilogFile / the Bluesim
                      object reuse, decided by a one-second mtime comparison in
                      StaleUtils.allFreshVs, so the word flips between runs);
                      the 'Verilog file' lines are also moved to a sorted block
                      at the end of the transcript, because a reuse is reported
                      before the other modules' code generation and a creation
                      after it (the write order stays visible in the 'Elaborated
                      module file created:' lines, which are left alone, as are
                      the '<engine> object' lines, whose order is a known leak,
                      bluesim-package-map-order); blank the numbers of ' elapsed time: CPU 0.12s, real
                      0.34s' lines (TopUtils.printElapsed under -v); drop the
                      GHC RTS statistics of a bsc run with +RTS -s or -S (the
                      -S column header and rows, the -s summary); and reduce
                      "make[N]: Entering/Leaving directory '<dir>'" to the
                      word Entering/Leaving (the level is one more under the
                      parallel driver than under the serial one, the directory
                      is the tree's own path)
  .diff-out           drop the timestamps of the '--- file<TAB>date' and
                      '+++ file<TAB>date' header lines of a harness diff
Everything else is byte-exact.

A file present in only one archive counts as a difference: it must be ignored
or allow-listed like any other.

Scope.  The allow-list is shared by every run, but a partial run (ONLY_GROUPS,
or a CI bundle) archives only its own groups' files, so it must not report the
other groups' entries as stale.  With --scope-groups "g1 g2 ..." staleness is
checked only for allow-list entries that are
  (a) under bsc.<g>/ for a scoped group g (running group g runs every .exp
      under that directory), or
  (b) in a directory that holds at least one file archived in this run (this
      covers long_tests, whose .exp files live under other groups'
      directories; no testsuite directory holds more than one .exp file).
Entries out of scope are counted in the summary and never reported stale.  A
differing file that is not allowed fails whatever the scope.  Without
--scope-groups every entry is in scope: the full run is the authority.

Exit status:
  0  green: every difference is allow-listed and every entry is live
  1  at least one file differs (or is present in only one archive) that is
     neither allow-listed nor ignored
  2  stale allow-list entries (identical now, absent from both archives, or
     shadowed by an ignore pattern), unless --allow-stale is given
  3  usage or I/O error
Status 1 wins over 2 when both apply.

Outputs (PREFIX is --out):
  PREFIX.differ    every file that differs after normalisation, one path per line
  PREFIX.new       the failures: path, kind (differ | only-in-A | only-in-B)
  PREFIX.stale     stale allow-list entries: path, reason
  PREFIX.outofscope allow-list entries not checked for staleness (--scope-groups)
  PREFIX.ignored   files an ignore pattern removed: path, pattern
  PREFIX.onesided  files present in one archive only: path, A|B, allowed|NEW
  --write-allowlist F   a fresh allow-list of what differs today, keeping the
                        root_id and note of entries that are still live and
                        marking new files UNCLASSIFIED
"""

import argparse
import fnmatch
import os
import re
import sys
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor

SKIP_TOP_DIRS = {"_sum", "_log"}
SKIP_BASENAMES = {"time.out", "groups.list"}
CHUNK = 1 << 20
UNCLASSIFIED = "UNCLASSIFIED"


def die(msg, status=3):
    print(f"compare.py: {msg}", file=sys.stderr)
    sys.exit(status)


def warn(msg):
    print(f"compare.py: warning: {msg}", file=sys.stderr)


class Parser(argparse.ArgumentParser):
    """argparse exits 2 on bad usage; the gate reserves 2 for stale entries."""

    def error(self, message):
        self.print_usage(sys.stderr)
        die(message)


# ---------------------------------------------------------------- normalisers
# Each normaliser rewrites or drops exactly one kind of line that no compiler
# ordering can reach (see the module docstring); normalisers_for() says which
# run on a file, by its name.  check-normalisers.py (next to this file) runs
# each one on samples captured from gate archives.

SRC_HEADER_RE = re.compile(rb"^// (?:On|Generated by) |^ \* On ")
VCD_DATE_RE = re.compile(rb"\$date\b.*?\$end", re.S)
HEX_RE = re.compile(rb"0x[0-9a-fA-F]+")


def norm_src(data):
    return b"".join(
        line
        for line in data.splitlines(keepends=True)
        if not SRC_HEADER_RE.match(line) and b"--creation_time" not in line
    )


def norm_vcd(data):
    return VCD_DATE_RE.sub(b"", data, count=1)


def norm_vvp(data):
    return HEX_RE.sub(b"0xADDR", data)


# model_*.cxx: get_creation_time() returns the build time, written as a
# calendar-time comment and the epoch literal on the next line
# (SimBlocksToC.hs gct_def):
#       /* Mon Oct  5 01:24:11 UTC 2026 */
#       return 1791163451llu;
# The pair goes together; the return line alone is left as it is.
CTIME_COMMENT_RE = re.compile(
    rb"^\s*/\* [A-Z][a-z]{2} [A-Z][a-z]{2} [ \d]\d \d\d:\d\d:\d\d [A-Za-z]+ \d{4} \*/\r?\n?$")
CTIME_RETURN_RE = re.compile(rb"^\s*return \d+llu;\r?\n?$")


def norm_model_ctime(data):
    lines = data.splitlines(keepends=True)
    out = []
    i = 0
    while i < len(lines):
        if (CTIME_COMMENT_RE.match(lines[i]) and i + 1 < len(lines)
                and CTIME_RETURN_RE.match(lines[i + 1])):
            i += 2
            continue
        out.append(lines[i])
        i += 1
    return b"".join(out)


# bsc transcripts.  The four line kinds, each anchored to the whole line:
#  - 'Verilog file reused: X.v' / '<engine> object reused: X.{h,o}' against
#    'created:' (bsc.hs reuseVerilogFile and the Bluesim object reuse; the
#    choice is a one-second mtime comparison, StaleUtils.allFreshVs).  A
#    Verilog reuse is reported when the decision is made, before the other
#    modules' code generation, and a creation after the file is written, so
#    the 'Verilog file' line moves as well: those lines are taken out and
#    re-emitted, sorted, at the end of the transcript.  Every .v write is
#    paired with an 'Elaborated module file created:' line, which stays in
#    place, so the write order is still compared; the '<engine> object'
#    lines stay in place too, since their order is the known leak
#    bluesim-package-map-order (ABinUtil m_abmis_used)
#  - ' elapsed time: CPU 0.12s, real 0.34s' (TopUtils.printElapsed, -v)
#  - the GHC RTS statistics a test asks for with +RTS -s or +RTS -S: the -S
#    column header and its per-GC rows (interleaved with the transcript), and
#    the -s summary lines, all in GHC's fixed wording
#  - "make[2]: Entering directory '/path/to/tree/testsuite/x'" (GNU make
#    under bsc's -parallel-sim-link or a test's own make; the level counts
#    the makes above, the directory is the tree's own path)
VFILE_RE = re.compile(rb"^Verilog file (created|reused): ")
OBJ_REUSED_RE = re.compile(rb"^([A-Za-z]+ object) reused: ")
ELAPSED_RE = re.compile(rb"^( elapsed time: CPU )[0-9.eE+-]+(s, real )[0-9.eE+-]+(s\r?\n?)$")
MAKE_DIR_RE = re.compile(rb"^make\[\d+\]: (Entering|Leaving) directory '[^']*'(\r?\n?)$")
RTS_LINE_RES = [re.compile(rx) for rx in (
    rb"^\s*Alloc\s+Copied\s+Live\s+GC\s+GC\s+TOT\s+TOT\s+Page Flts\s*$",
    rb"^\s*bytes\s+bytes\s+bytes\s+user\s+elap\s+user\s+elap\s*$",
    rb"^\s*\d+\s+\d+\s+\d+(\s+\d+\.\d+){4}\s+\d+\s+\d+\s+\(Gen:\s+\d+\)\s*$",
    rb"^\s*\d+\s+\d+\.\d+\s+\d+\.\d+\s*$",
    rb"^\s*[\d,]+ bytes (allocated in the heap|copied during GC|maximum residency \(\d+ sample\(s\)\)|maximum slop)\s*$",
    rb"^\s*[\d,]+ M[i]?B total memory in use \(\d+ M[i]?B lost due to fragmentation\)\s*$",
    rb"^\s*Tot time \(elapsed\)\s+Avg pause\s+Max pause\s*$",
    rb"^\s*Gen\s+\d+\s+\d+ colls,\s+\d+ par\s+[\d.]+s\s+[\d.]+s\s+[\d.]+s\s+[\d.]+s\s*$",
    rb"^\s*(INIT|MUT|GC|EXIT|Total)\s+time\s+[\d.]+s\s+\(\s*[\d.]+s elapsed\)\s*$",
    rb"^\s*%GC\s+time\s+[\d.]+%\s+\([\d.]+% elapsed\)\s*$",
    rb"^\s*Alloc rate\s+[\d,]+ bytes per MUT second\s*$",
    rb"^\s*Productivity\s+[\d.]+% of total user, [\d.]+% of total elapsed\s*$",
    rb"^\s*TASKS: \d+ \(\d+ bound, \d+ peak workers \(\d+ total\), using -N\d+\)\s*$",
    rb"^\s*SPARKS: .*$",
    rb"^\s*Parallel GC work balance: .*$",
)]


def norm_transcript(data):
    out = []
    vfiles = []   # the 'Verilog file' lines, re-emitted sorted at the end
    for line in data.splitlines(keepends=True):
        m = VFILE_RE.match(line)
        if m:
            vfiles.append(b"Verilog file created: " + line[m.end():].rstrip(b"\r\n") + b"\n")
            continue
        m = OBJ_REUSED_RE.match(line)
        if m:
            line = m.group(1) + b" created: " + line[m.end():]
        else:
            m = ELAPSED_RE.match(line)
            if m:
                line = m.group(1) + b"N" + m.group(2) + b"N" + m.group(3)
            else:
                m = MAKE_DIR_RE.match(line)
                if m:
                    line = b"make: " + m.group(1) + b" directory" + m.group(2)
                elif any(rx.match(line) for rx in RTS_LINE_RES):
                    continue
        out.append(line)
    return b"".join(out) + b"".join(sorted(vfiles))


# Harness diffs (compare_file in config/unix.exp runs diff -u): the two header
# lines carry the files' mtimes after a TAB.
DIFF_HEADER_RE = re.compile(
    rb"^((?:---|\+\+\+) .*?)\t\d{4}-\d\d-\d\d \d\d:\d\d:\d\d(?:\.\d+)? [+-]\d{4}(\r?\n?)$")


def norm_diff_header(data):
    return b"".join(DIFF_HEADER_RE.sub(rb"\1\2", line)
                    for line in data.splitlines(keepends=True))


TRANSCRIPT_RE = re.compile(r"\.bsc(?:-[a-z]+)*-out$")


def normalisers_for(rel):
    """The normalisers that run on this file, in order; [] for byte-exact."""
    name = rel.rsplit("/", 1)[-1]
    if name.endswith((".v", ".sv", ".cxx", ".h", ".c")):
        if name.startswith("model_") and name.endswith(".cxx"):
            return [norm_src, norm_model_ctime]
        return [norm_src]
    if name.endswith((".vcd", ".fst-vcd")):
        return [norm_vcd]
    if name.endswith((".inline-reg", ".no-inline-reg")):
        return [norm_vvp]
    if TRANSCRIPT_RE.search(name):
        return [norm_transcript]
    if name.endswith(".diff-out"):
        return [norm_diff_header]
    return []


def normalise(rel, data):
    for norm in normalisers_for(rel):
        data = norm(data)
    return data


# ------------------------------------------------------------------- archives

def walk(root):
    """Map relative path -> size for every regular file that takes part."""
    if not os.path.isdir(root):
        die(f"not a directory: {root}")
    files = {}
    stack = [""]
    while stack:
        rel = stack.pop()
        here = os.path.join(root, rel) if rel else root
        try:
            with os.scandir(here) as it:
                for e in it:
                    name = e.name
                    r = f"{rel}/{name}" if rel else name
                    if e.is_symlink():
                        continue
                    if e.is_dir(follow_symlinks=False):
                        if not rel and name in SKIP_TOP_DIRS:
                            continue
                        stack.append(r)
                    elif e.is_file(follow_symlinks=False):
                        if name in SKIP_BASENAMES:
                            continue
                        files[r] = e.stat(follow_symlinks=False).st_size
        except OSError as exc:
            die(f"cannot read {here}: {exc}")
    return files


def same_bytes(pa, pb, size_a, size_b):
    if size_a != size_b:
        return False
    with open(pa, "rb") as fa, open(pb, "rb") as fb:
        while True:
            a = fa.read(CHUNK)
            b = fb.read(CHUNK)
            if a != b:
                return False
            if not a:
                return True


def files_equal(args):
    """True when the file is the same in both archives (after normalisation)."""
    pa, pb, size_a, size_b, rel = args
    if same_bytes(pa, pb, size_a, size_b):
        return True
    if not normalisers_for(rel):
        return False
    with open(pa, "rb") as f:
        da = f.read()
    with open(pb, "rb") as f:
        db = f.read()
    return normalise(rel, da) == normalise(rel, db)


# ---------------------------------------------------------------------- lists

def list_lines(path):
    try:
        with open(path, encoding="utf-8") as f:
            for lineno, raw in enumerate(f, 1):
                line = raw.rstrip("\n")
                if not line.strip() or line.lstrip().startswith("#"):
                    continue
                yield lineno, line
    except OSError as exc:
        die(f"cannot read {path}: {exc}")


def clean_path(p):
    p = p.strip()
    return p[2:] if p.startswith("./") else p


def read_allowlist(path):
    """path -> (root_id, note)"""
    entries = {}
    order = []
    for lineno, line in list_lines(path):
        parts = line.split("\t")
        rel = clean_path(parts[0])
        root = parts[1].strip() if len(parts) > 1 else ""
        if not rel or not root:
            die(f'{path}:{lineno}: expected "path<TAB>root_id<TAB>note"')
        if rel in entries:
            die(f"{path}:{lineno}: duplicate entry for {rel}")
        entries[rel] = (root, "\t".join(parts[2:]).strip())
        order.append(rel)
    if order != sorted(order):
        warn(f"{path} is not sorted by path")
    return entries


def read_ignore(path):
    """[(pattern, reason, compiled regex)]"""
    pats = []
    seen = set()
    for lineno, line in list_lines(path):
        parts = line.split("\t")
        pat = clean_path(parts[0])
        reason = parts[1].strip() if len(parts) > 1 else ""
        if not pat or not reason:
            die(f'{path}:{lineno}: expected "glob<TAB>reason" (a reason is required)')
        if pat in seen:
            die(f"{path}:{lineno}: duplicate pattern {pat}")
        seen.add(pat)
        pats.append((pat, reason, re.compile(fnmatch.translate(pat))))
    return pats


def ignored_by(rel, patterns):
    for pat, _reason, rx in patterns:
        if rx.match(rel):
            return pat
    return None


# -------------------------------------------------------------------- reports

def ext_of(rel):
    name = rel.rsplit("/", 1)[-1]
    return name.rsplit(".", 1)[1] if "." in name else "(noext)"


def print_counter(title, counter, indent="   "):
    print(title)
    if not counter:
        print(f"{indent}(none)")
    for key, n in sorted(counter.items(), key=lambda kv: (-kv[1], kv[0])):
        print(f"{indent}{n:6d} {key}")


def write_lines(path, lines):
    try:
        with open(path, "w", encoding="utf-8") as f:
            for line in lines:
                f.write(line + "\n")
    except OSError as exc:
        die(f"cannot write {path}: {exc}")


def write_allowlist(path, live, allow):
    """live: {rel: kind}; allow: the allow-list read at the start."""
    header = [
        "# bsc determinism gate: files that still differ between a normal run of the",
        "# testsuite and one with -reverse-intern-order (util/determinism/compare.py).",
        "# TAB-separated: path (relative to testsuite/), root_id, note.  Sorted by path.",
        "# The list only shrinks: compare.py fails on entries that no longer differ.",
    ]
    rows = []
    for rel in sorted(live):
        if rel in allow:
            root, note = allow[rel]
        else:
            root, note = UNCLASSIFIED, {"differ": "differs", "only-in-A": "only in A",
                                        "only-in-B": "only in B"}[live[rel]]
        rows.append(f"{rel}\t{root}\t{note}")
    write_lines(path, header + rows)


# ----------------------------------------------------------------------- main

def main():
    ap = Parser(
        prog="compare.py",
        description="Compare two testsuite archives against the determinism allow-list.",
        epilog="exit status: 0 green, 1 new differences, 2 stale allow-list entries, 3 error",
    )
    ap.add_argument("archiveA")
    ap.add_argument("archiveB")
    ap.add_argument("--allowlist", required=True, metavar="F")
    ap.add_argument("--ignore", required=True, metavar="F")
    ap.add_argument("--out", required=True, metavar="PREFIX")
    ap.add_argument("--write-allowlist", metavar="F",
                    help="write a fresh allow-list of what differs today")
    ap.add_argument("--allow-stale", action="store_true",
                    help="report stale allow-list entries without failing")
    ap.add_argument("--scope-groups", metavar="GROUPS", default="",
                    help="space-separated testsuite groups this run covered: staleness is "
                         "checked only for entries under bsc.<group>/ or in a directory "
                         "that holds an archived file")
    ap.add_argument("--root-counts", action="store_true",
                    help="also print a per-root_id table with live, stale and per-extension counts")
    ap.add_argument("--jobs", type=int, default=min(8, os.cpu_count() or 1), metavar="N",
                    help="reader threads (default %(default)s)")
    args = ap.parse_args()

    A = os.path.abspath(args.archiveA)
    B = os.path.abspath(args.archiveB)
    if A == B:
        die("the two archives are the same directory")
    allow = read_allowlist(args.allowlist)
    patterns = read_ignore(args.ignore)
    out_dir = os.path.dirname(os.path.abspath(args.out))
    try:
        os.makedirs(out_dir, exist_ok=True)
    except OSError as exc:
        die(f"cannot create {out_dir}: {exc}")

    files_a = walk(A)
    files_b = walk(B)

    ignored = []          # (rel, pattern)
    pattern_hits = Counter()
    onesided = []         # (rel, side, allowed)
    to_compare = []
    for rel in sorted(set(files_a) | set(files_b)):
        pat = ignored_by(rel, patterns)
        if pat is not None:
            ignored.append((rel, pat))
            pattern_hits[pat] += 1
        elif rel not in files_b:
            onesided.append((rel, "A", rel in allow))
        elif rel not in files_a:
            onesided.append((rel, "B", rel in allow))
        else:
            to_compare.append(rel)

    jobs = [(os.path.join(A, rel), os.path.join(B, rel), files_a[rel], files_b[rel], rel)
            for rel in to_compare]
    try:
        with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
            equal = list(pool.map(files_equal, jobs, chunksize=64))
    except OSError as exc:
        die(f"cannot read an archived file: {exc}")

    same = 0
    differing = []        # rel
    for rel, eq in zip(to_compare, equal):
        if eq:
            same += 1
        else:
            differing.append(rel)

    # live: every path that still differs or is one-sided and is not ignored
    live = {rel: "differ" for rel in differing}
    for rel, side, _allowed in onesided:
        live[rel] = f"only-in-{side}"
    new = {rel: kind for rel, kind in live.items() if rel not in allow}
    allowed = {rel: kind for rel, kind in live.items() if rel in allow}

    scope_groups = args.scope_groups.split()
    scope_prefixes = tuple(f"bsc.{g}/" for g in scope_groups)
    archived_dirs = {os.path.dirname(rel) for rel in set(files_a) | set(files_b)}

    def in_scope(rel):
        if not scope_groups:
            return True
        return rel.startswith(scope_prefixes) or os.path.dirname(rel) in archived_dirs

    stale = []            # (rel, reason)
    out_of_scope = []     # rel
    ignored_set = {rel for rel, _pat in ignored}
    for rel in sorted(allow):
        if rel in live:
            continue
        if not in_scope(rel):
            out_of_scope.append(rel)
        elif rel in ignored_set:
            stale.append((rel, "ignored"))
        elif rel in files_a and rel in files_b:
            stale.append((rel, "identical"))
        else:
            stale.append((rel, "absent"))

    # ---- outputs
    out = args.out
    write_lines(out + ".differ", differing)
    write_lines(out + ".new", [f"{rel}\t{kind}" for rel, kind in sorted(new.items())])
    write_lines(out + ".stale", [f"{rel}\t{reason}" for rel, reason in stale])
    write_lines(out + ".ignored", [f"{rel}\t{pat}" for rel, pat in ignored])
    write_lines(out + ".onesided",
                [f"{rel}\t{side}\t{'allowed' if ok else 'NEW'}" for rel, side, ok in onesided])
    if scope_groups:
        write_lines(out + ".outofscope", out_of_scope)
    if args.write_allowlist:
        write_allowlist(args.write_allowlist, live, allow)

    # ---- summary
    n_only = {"A": Counter(), "B": Counter()}
    for rel, side, ok in onesided:
        n_only[side]["allowed" if ok else "NEW"] += 1
    n_diff_allowed = sum(1 for rel in differing if rel in allow)
    n_diff_new = len(differing) - n_diff_allowed

    print(f"compare.py: A = {A}")
    print(f"            B = {B}")
    print(f"   files found          A {len(files_a):6d}   B {len(files_b):6d}")
    print(f"   same                 {same:6d}")
    print(f"   differing, allowed   {n_diff_allowed:6d}")
    print(f"   differing, NEW       {n_diff_new:6d}")
    print(f"   stale allow-list     {len(stale):6d}"
          + (f"   ({', '.join(f'{n} {r}' for r, n in sorted(Counter(r for _, r in stale).items()))})"
             if stale else ""))
    print(f"   ignored              {len(ignored):6d}   ({len(patterns)} patterns)")
    for side in "AB":
        c = n_only[side]
        print(f"   only in {side}            {sum(c.values()):6d}"
              + (f"   (allowed {c['allowed']}, NEW {c['NEW']})" if c else ""))
    print(f"   allow-list entries   {len(allow):6d}   (live {len(allowed)}, stale {len(stale)}"
          + (f", out of scope {len(out_of_scope)}" if scope_groups else "") + ")")
    if scope_groups:
        print(f"   scope                {' '.join(scope_groups)}"
              f"   ({len(out_of_scope)} entries of other groups not checked for staleness)")

    by_ext = Counter(ext_of(rel) for rel in differing)
    print_counter("differing files by extension:", by_ext)
    by_root = Counter(allow[rel][0] if rel in allow else "(NEW)" for rel in live)
    print_counter("differing files by root_id (one-sided files included):", by_root)

    if args.root_counts:
        print("per root_id: live entries, stale entries, live by extension:")
        roots = defaultdict(lambda: {"live": 0, "stale": 0, "ext": Counter()})
        for rel, (root, _note) in allow.items():
            if rel in live:
                roots[root]["live"] += 1
                roots[root]["ext"][ext_of(rel)] += 1
            else:
                roots[root]["stale"] += 1
        for rel in new:
            roots["(NEW)"]["live"] += 1
            roots["(NEW)"]["ext"][ext_of(rel)] += 1
        width = max([len(r) for r in roots] + [8])
        print(f"   {'root_id':<{width}}  {'live':>5} {'stale':>5}  by extension")
        for root, info in sorted(roots.items(), key=lambda kv: (-kv[1]['live'], kv[0])):
            exts = " ".join(f"{e} {n}" for e, n in
                            sorted(info["ext"].items(), key=lambda kv: (-kv[1], kv[0])))
            print(f"   {root:<{width}}  {info['live']:5d} {info['stale']:5d}  {exts}")

    # A partial run cannot see most of the patterns' files; only the full run
    # can tell that a pattern is dead.
    unused = [pat for pat, _r, _rx in patterns if pattern_hits[pat] == 0]
    if unused and not scope_groups:
        warn(f"{len(unused)} ignore pattern(s) matched no file: {' '.join(unused)}")

    print(f"outputs: {out}.{{differ,new,stale,ignored,onesided"
          + (",outofscope}" if scope_groups else "}")
          + (f" and allow-list {args.write_allowlist}" if args.write_allowlist else ""))

    status = 0
    verdict = "GREEN"
    if stale and not args.allow_stale:
        status, verdict = 2, f"RED: {len(stale)} stale allow-list entries (see {out}.stale)"
    elif stale:
        verdict = f"GREEN (with {len(stale)} stale allow-list entries, --allow-stale)"
    if new:
        status = 1
        verdict = (f"RED: {len(new)} new differing or one-sided files (see {out}.new)"
                   + (f"; also {len(stale)} stale allow-list entries" if stale else ""))
    print(f"result: {verdict}")
    return status


if __name__ == "__main__":
    sys.exit(main())
