#!/bin/sh
# One-command (re)build of the bsc cabal library for script/ghci use.
#
# Run this:
#   * once after cloning (after `make install-src` has built the vendored
#     solver libraries), and
#   * again WHENEVER the compiler sources change or a make build has been
#     done at a new git commit.
#
# The second point is a correctness requirement, not hygiene: .bo/.ba files
# embed the build version string (git hash, via BuildVersion.hs), and the
# library refuses .ba files whose stamp differs from its own
# (ABinUtil.decodeABin -> EBinFileVerMismatch).  The library and the bsc
# that produced your .ba files must be built from the same BuildVersion.hs.

set -e
REPO=$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")
cd "$REPO"

# Vendored solver libraries must exist (normally built by `make install-src`)
for f in src/vendor/stp/lib/libstp.so src/vendor/yices/lib/libyices.so; do
    if [ ! -e "$f" ]; then
        echo "setup.sh: $f missing - build the vendor libs first:" >&2
        echo "  make -C src/vendor/stp install PREFIX=$REPO/inst" >&2
        echo "  make -C src/vendor/yices install PREFIX=$REPO/inst" >&2
        exit 1
    fi
done

# Generated modules (same scripts the make build runs).
# update-build-version.sh runs under `set -u` and reads NOGIT and
# NOUPDATEBUILDVERSION from the environment; the make build exports
# them with defaults (src/comp/Makefile), so default them here too.
(cd src/comp && \
     NOGIT="${NOGIT:-0}" NOUPDATEBUILDVERSION="${NOUPDATEBUILDVERSION:-0}" \
     ./update-build-version.sh && \
     ./update-build-system.sh)

# Machine-local cabal configuration: ghc-pkg requires ABSOLUTE library dirs
# at registration time, so these cannot live in the committed bsc.cabal.
if [ ! -f cabal.project.local ]; then
    cat > cabal.project.local <<EOF
-- Generated by util/bluehs/setup.sh (machine-local; not for commit)
package bsc
  extra-lib-dirs: $REPO/src/vendor/stp/lib
  extra-lib-dirs: $REPO/src/vendor/yices/lib
EOF
    echo "setup.sh: wrote cabal.project.local"
fi

cabal build
echo "setup.sh: done - try: util/bluehs/bin/dumpbo inst/lib/Libraries/Arbiter.bo"
